### ISSUE TITLE
Error en la URL de comunicación online

### ISSUE THREAD

**Issue by Orioldu** [juanmirod/woocommerce-ceca-gateway#14]
Buenos días,

Configurando el plugin en woocommerce y ya resuelto el problema de que los pedidos no aparezcan como pagados, aparece un nuevo problema:

Una vez realizas el pago en la pasarela de Cecabank, tienes que apretar el botón de "Aceptar" para volver a la web y que esta registre el pedido como pagado, he hablado con los técnicos de cecabank y eso es debido a un error en la URL de comunicación, en el parámetro url_ok hay que poner la url que cecabank te facilita en tu consola TPV en vez de la url que hay agregada actualmente, como es una url que cada comercio tiene la suya propia, habría que añadir un apartado en el back-office de configuración del plugin en el que puedas insertar tu URL, adjunto una captura de pantalla del panel de cecabank en el que encuentras tu URL propia, con esa URL la conexión es de servidor a servidor, y no hace falta ninguna acción por parte del cliente, adjunto captura de pantalla http://prntscr.com/gv423e

**Comment by Orioldu** [comment]
Problema resuelto, en el TPV Virtual de CECABANK, modificar la URL existente por:

https://tudominio.com/?wc-api=wc_gateway_ceca

**Comment by juanmirod** [comment]
Gracias de nuevo por los comentarios, en este caso la url es diferente de lo que indica el README? No veo la diferencia pero a lo mejor se me está escapando algo.

**Comment by Orioldu** [comment]
Disculpa @juanmirod, no me paré a leer el Readme con las prisas T.T según lo que me explicaron desde Cecabank, la URL que ellos daban era la que tenía que poner en vez de cambiarla por la existente en el plugin. Disculpa de nuevo, puedes cerrar la incidencia
