### ISSUE TITLE
Pending to processing when pay accepted

### ISSUE THREAD

**Issue by sardinax** [juanmirod/woocommerce-ceca-gateway#4]
Buenas,

El plugin funciona genial. Me gustaría saber como puedo hacer para que cuando vuelva de la página del banco después de aceptar el pago, el pedido pase a processing. Con este modo de pago me retorna pending, y ello no activa el envío de correos. 

Gracias de antemano,
Krist

**Comment by Raiderpoer** [comment]
¡Hola!

Para que esto surja, usted debe configurar varios campos en su TPV de Ceca.
1. Vaya a su configuración y marque "Comunicación on-line OK" en sí.
2. En el campo que se encuentra a la derecha en el cual poner "URL online OK", usted debe poner: 
- http://suweb.com/?wc-api=wc_gateway_ceca
- https://suweb.com/?wc-api=wc_gateway_ceca

Debe usar uno u otro dependiendo de que usted tenga SSL o no. Después de esto lo que usted indica funcionará perfectamente.

Disculpe la demora al responder.

Gracias
Saludos Cordiales

**Comment by juanmirod** [comment]
Gracias por la aclaración @Raiderpoer, creo que es lo mismo que están en readme, así que cierro el hilo. 

Saludos

**Comment by sardinax** [comment]
Buenas,

Perdona por la espera, no había visto la respuesta @Raiderpoer. 

La url ya estaba puesta (http://.../?wc-api=wc_gateway_ceca) y no pasaba a processing. He visto que justo encima de esa configuración el cliente tiene marcado Tipo de comercio: Seguro. ¿Esto requiere enviar la URL OK como https y con ello tener un servidor con SSL?

Gracias

**Comment by sardinax** [comment]
Hola de nuevo,

He hablado con el banco, y me comentan que no es necesario tener certificado SSL. ¿Que puede estar fallando?

Saludos y gracias de nuevo

**Comment by juanmirod** [comment]
Hola @sardinax

Si intentas conectar con una página que usa https sin certificado seguramente el navegador o algún otro agente intermedio ebloquee la petición. Con lo que sí necesitas el certificado si es que quieres utilizar SSL (lo cuál es totalmente recomendable cuando estamos hablando de pasarelas de pago). 

Si decides no utilizar SSL y utilizar el protocolo http, asegurate de que está bien enlazado en todos sitios. Siento no tener más datos que darte pero sin ver el caso en concreto y haciendo tanto tiempo que no utilizo el plugin no puedo decirte más.

Saludos

**Comment by sardinax** [comment]
Hola @juanmirod 

Gracias por la respuesta, no creo que sea problema del SSL, el pago se realiza correctamente y parece estar bien configurado. Lo único que al volver de la web del banco no pasa el pedido a processing... Seguiré investigando.

Saludos

**Comment by sardinax** [comment]
Hola de nuevo,

Siguiendo el issue de comunicacion online, este problema está solucionado: https://github.com/juanmirod/woocommerce-ceca-gateway/issues/1
